on:
  pull_request:
     branches:
         - main
         - develop
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: maven
        - uses: actions/checkout@v3.0.1
        - name: Install Atlas
          run: |
            curl -sSf https://atlasgo.sh | sh
        - run: |
            atlas migrate apply --dir file://migrations/ -u 'mysql://root:pass@localhost:3306/dev'
        - run: |
            echo "Run your tests here!"
        - name: Build with Maven
          run: mvn -B clean package --file pom.xml
